### PR TITLE
Typo fix: Loose > Lose

### PR DESCRIPTION
**Pull request by gingerbeardman**

### CODE REVIEW

**Comment by E-Sh4rk** [comment]
Thanks for the contribution! It looks like I still have progress to make in english ^^ Some occurences of "Loose" are still unchanged in Bot.cs, thus it does not compile anymore.
Please can you update this file too before I merge the patch?

**Comment by gingerbeardman** [comment]
Have done so.

Sorry for multiple PR, I am using GitHub web interface in this instance.

**Comment by E-Sh4rk** [comment]
Thanks! Merging.

**Comment by gingerbeardman** [comment]
Thanks for the bot! I'm reading the physics/collision implementation with great interest.

**Pull request merged**
